id: 9f5fe19d-f1ea-4fd3-8389-1e2ca267ab00
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: Yoda Speak - Playbook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 8e4afb2a-34b7-4b27-8cda-5121fd23a9ec
    type: start
    task:
      id: 8e4afb2a-34b7-4b27-8cda-5121fd23a9ec
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 950b35ba-280f-4888-8386-b9294a7edf9b
    type: regular
    task:
      id: 950b35ba-280f-4888-8386-b9294a7edf9b
      version: -1
      name: yoda-speak-translate
      description: Translate a text from English to Yoda
      script: Yoda Speak|||yoda-speak-translate
      type: regular
      iscommand: true
      brand: Yoda Speak
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      text:
        simple: ${incident.details}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 4b0e6c5a-b51a-4e48-8996-fa1d398a36b6
    type: regular
    task:
      id: 4b0e6c5a-b51a-4e48-8996-fa1d398a36b6
      version: -1
      name: Print
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: ${YodaSpeak.TheForce.Translation}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
